### ISSUE TITLE
Unintuitive heterocomplex formula

### ISSUE THREAD

**Issue by hallba** [soli/casq#4]
[Archive.zip](https://github.com/soli/casq/files/6540536/Archive.zip)

The function of heterocomplexes is built from a series of "or" operations derived from constituent parts e.g. if

A + B -> AB

The function of AB is 

(Or (A=1) (B=1))

This is non-intuitive behaviour as it implies the complex can be formed from A or B alone. I believe this arises from model simplification where A and B are removed, and replaced by direct transitions from their input. Please confirm that this is the expected behaviour. Compressed example inputs/outputs attached.

**Comment by soli** [comment]
Indeed this is non-intuitive and due to the model simplification pass… I'll look into it because that could actually be quite a problem in many cases. Thanks for the report!

**Comment by soli** [comment]
The semantics of the heterodimer-association changed after some lengthy discussions. It now only merges **inputs**… hence completely removing them.
